import { getExistingBookings } from "./sheets.js";
import { formatDateForSheet, formatDisplayTime, getLondonNow, getTodayMinutes, parseTimeToMinutes } from "./helpers.js";

function slotMinutes(config) { const configured = Number(config?.bookingSettings?.bookingIntervalMinutes); return Number.isInteger(configured) && configured > 0 ? configured : 30; }
function getMaxBookingsPerSlot(config) { const value = Number(config?.bookingSettings?.maxBookingsPerSlot); return Number.isInteger(value) && value > 0 ? value : 1; }
function roundToConfiguredSlot(minutes, config) { const interval = slotMinutes(config); return Math.ceil(minutes / interval) * interval; }
function parseClockPart(hourText, minuteText, meridiemText) { let hour=Number(hourText); const minute=Number(minuteText||0); const meridiem=String(meridiemText||"").toLowerCase(); if(!Number.isInteger(hour)||hour<1||hour>12||!Number.isInteger(minute)||minute<0||minute>59)return null; if(meridiem==="pm"&&hour!==12)hour+=12; if(meridiem==="am"&&hour===12)hour=0; return hour*60+minute; }
function parseOpeningRange(value) { const text=String(value||"").trim(); if(!text||/^closed$/i.test(text))return null; const match=text.match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*-\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)$/i); if(!match)return null; const open=parseClockPart(match[1],match[2],match[3]),close=parseClockPart(match[4],match[5],match[6]); if(open===null||close===null||close<=open)return null; return {open,close}; }
function bookingWindowForDate(date, config) { const match=String(date||"").match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/); if(!match)return null; const day=Number(match[1]),month=Number(match[2])-1,year=Number(match[3]),dateObj=new Date(year,month,day); if(dateObj.getFullYear()!==year||dateObj.getMonth()!==month||dateObj.getDate()!==day)return null; const weekday=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"][dateObj.getDay()]; const openingRange=parseOpeningRange(config?.openingHours?.[weekday]); if(!openingRange)return null; const earliest=parseTimeToMinutes(config?.bookingSettings?.earliestBookingTime),latest=parseTimeToMinutes(config?.bookingSettings?.latestBookingTime),duration=Number(config?.bookingSettings?.defaultBookingLengthMinutes),bookingDuration=Number.isFinite(duration)&&duration>0?duration:0,latestStart=openingRange.close-bookingDuration; return {open:earliest===null?openingRange.open:Math.max(openingRange.open,earliest),close:latest===null?latestStart:Math.min(latestStart,latest)}; }
function countBookingsForSlot(bookings,date,requestedMinutes){return bookings.filter(b=>b.date===date&&parseTimeToMinutes(b.time)===requestedMinutes).length;}
async function findNextAvailableSlot(date,requestedTime,config,existingBookings=null){let minutes=parseTimeToMinutes(requestedTime);if(minutes===null)return null;const window=bookingWindowForDate(date,config);if(!window||window.close<=window.open)return null;minutes=roundToConfiguredSlot(minutes,config);const today=formatDateForSheet(getLondonNow());if(date===today&&minutes<=getTodayMinutes())minutes=roundToConfiguredSlot(getTodayMinutes()+1,config);if(minutes<window.open)minutes=roundToConfiguredSlot(window.open,config);const bookings=existingBookings||await getExistingBookings();while(minutes<window.close){if(countBookingsForSlot(bookings,date,minutes)<getMaxBookingsPerSlot(config))return formatDisplayTime(minutes);minutes+=slotMinutes(config);}return null;}
export async function validateRequestedSlot(date,time,config){const requestedMinutes=parseTimeToMinutes(time);if(requestedMinutes===null)return{ok:false,reason:"invalid",suggestion:null};const window=bookingWindowForDate(date,config);if(!window)return{ok:false,reason:"closed",suggestion:null};if(requestedMinutes<window.open||requestedMinutes>=window.close){let suggestion=null;if(requestedMinutes<window.open){const bookings=await getExistingBookings();suggestion=await findNextAvailableSlot(date,formatDisplayTime(window.open),config,bookings);}return{ok:false,reason:"closed",suggestion};}if(requestedMinutes%slotMinutes(config)!==0){const bookings=await getExistingBookings();return{ok:false,reason:"not_on_interval",suggestion:await findNextAvailableSlot(date,time,config,bookings)};}const today=formatDateForSheet(getLondonNow());if(date===today&&requestedMinutes<=getTodayMinutes()){const bookings=await getExistingBookings();return{ok:false,reason:"past",suggestion:await findNextAvailableSlot(date,time,config,bookings)};}const bookings=await getExistingBookings();if(countBookingsForSlot(bookings,date,requestedMinutes)>=getMaxBookingsPerSlot(config))return{ok:false,reason:"taken",suggestion:await findNextAvailableSlot(date,time,config,bookings)};return{ok:true,reason:null,suggestion:null};}
